const ADD_IN_SELECTED_MOVIES = 'ADD_IN_SELECTED_MOVIES';
const RESTART_GAME = 'RESTART_GAME';
const IS_QUESSED = 'IS_QUESSED';
const SET_ACTIVE_MOVIE = 'SET_ACTIVE_MOVIE';
const SET_RIGHT_MOVIE = 'SET_RIGHT_MOVIE';
const SET_MOVIES = 'SET_MOVIES';
const TO_NEXT_PAGE = 'TO_NEXT_PAGE';
const SET_PAGES_PASSED = 'SET_PAGES_PASSED';
const PAUSE_DESCRIPTION = 'PAUSE_DESCRIPTION';
const PAUSE_RANDOM_MOVIE = 'PAUSE_RANDOM_MOVIE';
const RESET_PLAYBACKS = 'RESET_PLAYBACKS';
const START_DESCRIPTION = 'START_DESCRIPTION';
const START_RANDOM_MOVIE = 'START_RANDOM_MOVIE';
const STOP_DESCRIPTION = 'STOP_DESCRIPTION';
const STOP_RANDOM_MOVIE = 'STOP_RANDOM_MOVIE';
const ADD_SCORE = 'ADD_SCORE';
const REDUCE_LEVEL_SCORE = 'REDUCE_LEVEL_SCORE';
const IS_STARTED = 'IS_STARTED';
const SET_GAME_OVER = 'SET_GAME_OVER';
const SET_LANGUAGE = 'SET_LANGUAGE';

const GAME_DESCRIPTION =
  'In this exciting quiz you will have to guess the movie from its description. Be careful - for every wrong answer you will lose a point. Play and have fun!';

export {
  ADD_IN_SELECTED_MOVIES,
  GAME_DESCRIPTION,
  RESTART_GAME,
  IS_QUESSED,
  SET_ACTIVE_MOVIE,
  SET_RIGHT_MOVIE,
  SET_MOVIES,
  TO_NEXT_PAGE,
  SET_PAGES_PASSED,
  PAUSE_DESCRIPTION,
  PAUSE_RANDOM_MOVIE,
  RESET_PLAYBACKS,
  START_DESCRIPTION,
  START_RANDOM_MOVIE,
  STOP_DESCRIPTION,
  STOP_RANDOM_MOVIE,
  ADD_SCORE,
  REDUCE_LEVEL_SCORE,
  IS_STARTED,
  SET_GAME_OVER,
  SET_LANGUAGE,
};
